// <auto-generated />
using System;
using FleetManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FleetManagement.Infrastructure.Migrations
{
    [DbContext(typeof(FleetDbContext))]
    partial class FleetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FleetManagement.Core.Aggregates.BusAggregate.Bus", b =>
                {
                    b.Property<int>("BusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BusId"));

                    b.Property<string>("BusNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentMileage")
                        .HasColumnType("integer");

                    b.Property<decimal>("FuelTankCapacity")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("LastMaintenanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("NextMaintenanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("BusId");

                    b.HasIndex("BusNumber")
                        .IsUnique();

                    b.ToTable("Buses", (string)null);
                });

            modelBuilder.Entity("FleetManagement.Core.Aggregates.BusAggregate.MaintenanceRecord", b =>
                {
                    b.Property<int>("MaintenanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaintenanceId"));

                    b.Property<int>("BusId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DowntimeHours")
                        .HasColumnType("integer");

                    b.Property<bool>("IsWarranty")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("MaintenanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaintenanceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MileageAtMaintenance")
                        .HasColumnType("integer");

                    b.Property<string>("PartsReplaced")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MaintenanceId");

                    b.HasIndex("BusId");

                    b.HasIndex("MaintenanceDate");

                    b.ToTable("MaintenanceRecords", (string)null);
                });

            modelBuilder.Entity("FleetManagement.Core.Aggregates.DriverAggregate.Driver", b =>
                {
                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CurrentFatigueLevel")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("DriverNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LastRestDay")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DriverId");

                    b.HasIndex("DriverNumber")
                        .IsUnique();

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.ToTable("Drivers", (string)null);
                });

            modelBuilder.Entity("FleetManagement.Core.Aggregates.DriverAggregate.DriverShift", b =>
                {
                    b.Property<Guid>("DriverShiftId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<double>("FuelUsed")
                        .HasPrecision(8, 2)
                        .HasColumnType("double precision");

                    b.Property<double>("HoursWorked")
                        .HasPrecision(4, 2)
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("date");

                    b.Property<int>("TripsCompleted")
                        .HasColumnType("integer");

                    b.HasKey("DriverShiftId");

                    b.HasIndex("ShiftDate");

                    b.HasIndex("DriverId", "ShiftDate")
                        .IsUnique();

                    b.ToTable("DriverShifts", (string)null);
                });

            modelBuilder.Entity("FleetManagement.Core.Aggregates.OperationAggregate.DailyOperation", b =>
                {
                    b.Property<int>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OperationId"));

                    b.Property<TimeSpan>("ArrivalTime")
                        .HasColumnType("interval");

                    b.Property<int>("BusId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DelayMinutes")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("interval");

                    b.Property<decimal>("DistanceTraveled")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("FuelConsumed")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("OperationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PassengerCount")
                        .HasColumnType("integer");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OperationId");

                    b.HasIndex("BusId");

                    b.HasIndex("OperationDate");

                    b.HasIndex("RouteId");

                    b.ToTable("DailyOperations", (string)null);
                });

            modelBuilder.Entity("FleetManagement.Core.Aggregates.RouteAggregate.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RouteId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Distance")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("EndLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("EstimatedDuration")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("NumberOfStops")
                        .HasColumnType("integer");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RouteNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StartLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RouteId");

                    b.HasIndex("RouteNumber")
                        .IsUnique();

                    b.ToTable("Routes", (string)null);
                });

            modelBuilder.Entity("FleetManagement.Core.Aggregates.BusAggregate.Bus", b =>
                {
                    b.OwnsOne("FleetManagement.Core.ValueObjects.Money", "PurchasePrice", b1 =>
                        {
                            b1.Property<int>("BusId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("PurchasePrice");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("PurchaseCurrency");

                            b1.HasKey("BusId");

                            b1.ToTable("Buses");

                            b1.WithOwner()
                                .HasForeignKey("BusId");
                        });

                    b.Navigation("PurchasePrice")
                        .IsRequired();
                });

            modelBuilder.Entity("FleetManagement.Core.Aggregates.BusAggregate.MaintenanceRecord", b =>
                {
                    b.HasOne("FleetManagement.Core.Aggregates.BusAggregate.Bus", null)
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FleetManagement.Core.ValueObjects.Money", "Cost", b1 =>
                        {
                            b1.Property<int>("MaintenanceRecordMaintenanceId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Cost");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("CostCurrency");

                            b1.HasKey("MaintenanceRecordMaintenanceId");

                            b1.ToTable("MaintenanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceRecordMaintenanceId");
                        });

                    b.Navigation("Cost")
                        .IsRequired();
                });

            modelBuilder.Entity("FleetManagement.Core.Aggregates.DriverAggregate.DriverShift", b =>
                {
                    b.HasOne("FleetManagement.Core.Aggregates.DriverAggregate.Driver", null)
                        .WithMany("Shifts")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetManagement.Core.Aggregates.OperationAggregate.DailyOperation", b =>
                {
                    b.HasOne("FleetManagement.Core.Aggregates.BusAggregate.Bus", null)
                        .WithMany()
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FleetManagement.Core.Aggregates.RouteAggregate.Route", null)
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("FleetManagement.Core.ValueObjects.Money", "FuelCost", b1 =>
                        {
                            b1.Property<int>("DailyOperationOperationId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("FuelCost");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("FuelCostCurrency");

                            b1.HasKey("DailyOperationOperationId");

                            b1.ToTable("DailyOperations");

                            b1.WithOwner()
                                .HasForeignKey("DailyOperationOperationId");
                        });

                    b.OwnsOne("FleetManagement.Core.ValueObjects.Money", "Revenue", b1 =>
                        {
                            b1.Property<int>("DailyOperationOperationId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Revenue");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("RevenueCurrency");

                            b1.HasKey("DailyOperationOperationId");

                            b1.ToTable("DailyOperations");

                            b1.WithOwner()
                                .HasForeignKey("DailyOperationOperationId");
                        });

                    b.Navigation("FuelCost")
                        .IsRequired();

                    b.Navigation("Revenue")
                        .IsRequired();
                });

            modelBuilder.Entity("FleetManagement.Core.Aggregates.RouteAggregate.Route", b =>
                {
                    b.OwnsOne("FleetManagement.Core.ValueObjects.Money", "EstimatedFuelCost", b1 =>
                        {
                            b1.Property<int>("RouteId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("EstimatedFuelCost");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("FuelCostCurrency");

                            b1.HasKey("RouteId");

                            b1.ToTable("Routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });

                    b.Navigation("EstimatedFuelCost")
                        .IsRequired();
                });

            modelBuilder.Entity("FleetManagement.Core.Aggregates.BusAggregate.Bus", b =>
                {
                    b.Navigation("MaintenanceRecords");
                });

            modelBuilder.Entity("FleetManagement.Core.Aggregates.DriverAggregate.Driver", b =>
                {
                    b.Navigation("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
